import Head from "next/head";
import Header from "@/components/header";
import Hero from "@/components/hero";
import Content from "@/components/content";
import Matrix from "@/components/matrix";
import Blogs from "@/components/blogs";
import Footer from "@/components/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Content />
      <Matrix />
      <Blogs />
      <Footer />
    </>
  );
}
